[server]
headless = true
address = "0.0.0.0"
port = 5000
enableXsrfProtection = true

[client]
showErrorDetails = false

[global]
# Don't show sensitive information in error messages
showWarningOnDirectExecution = false

[browser]
gatherUsageStats = false